apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configurations:
  - configs/varreference.yaml

resources:
  - cfg-x.yaml
  - pod.yaml

vars:
  - name: COLOR
    objref:
      kind: ConfigMap
      name: cfg
      apiVersion: v1
    fieldref:
      fieldpath: data.color