apiVersion: v1
kind: Pod
metadata:
  name: pod
  annotations:
    app1: $(APP1)
spec:
  containers:
    - name: pod
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "printenv; sleep 100" ]